[WIP] Update banner interaction logging
wmde/community-banners-until-2022 pull request #11
Opened 2020-05-06 15:11 UTC by Abban

https://phabricator.wikimedia.org/T250791

2020-05-11 16:32 UTC, KaiNissen requested changes
Some minor changes required to make this work.

2020-05-11 16:32 UTC, KaiNissen commented on shared/EventLoggingTracker.js
> +					userId: mw.user.id
I think, `mw.user.getId()` is what we want.

The schema defines this field as `userID` (capital D).

2020-05-11 16:32 UTC, KaiNissen commented on shared/EventLoggingTracker.js
> +			userId: mw.user.id
Same here.

2020-05-11 16:32 UTC, KaiNissen commented on occasional_editors/Banner.js
> +const BANNER_SEEN_TRACK_RATIO = 0.01;
Banners are shown to a very limited group of users, so we should increase this to `1`.

2020-05-11 16:35 UTC, KaiNissen commented on shared/EventLoggingTracker.js
> +		if ( Math.random() >= trackingRatio ) {
Shouldn't this be `<=`?

2020-05-14 08:40 UTC, gbirke approved these changes

2020-06-11 09:16 UTC, merged